
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/sampleDB?createDatabaseIfNotExist=true
    password: shawon
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update


server:
  port: 8080

jwt:
  secret: secretkey123
